### ISSUE TITLE
Improving README

### ISSUE THREAD

**Issue by skars82** [statisticsnorway/ssb-pickmdl#9]
I suggest that you a add short reasoning for why this package was created at the top og the README. I.e. "this package was created to extend the functionality of RJdemetra...". 

I also suggest that you explicitly have a section about installation. Are the dependencies the same as for RJdemetra, then it should be said explicitly and with a link to the installation-guide of RJdemetra.

**Comment by olangsrud** [comment]
Thanks. README is now updated.
